### ISSUE TITLE
Unreal Engine 5.4 Support

### ISSUE THREAD

**Issue by Aeryes** [P1ayer-1/Libtorch-UE5#10]
This should get assigned the question label if there is one.

Has anyone tested this plugin on Unreal Engine 5.4 yet? I'm wondering if it is compatible.

**Comment by Jacksparrow2525** [comment]
No. Many compile issues from not just LibTorch but the plugin code itself

**Comment by Aeryes** [comment]
> No. Many compile issues from not just LibTorch but the plugin code itself

Is the original author of the plugin still active?

**Comment by P1ayer-1** [comment]
This has already been addressed in #8 . The master branch supports 5.4.x. The Unreal 5.4.x/LibTorch 2.4.x release will be available in the near future.
